name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: |
          bun run lint:strict
          cd packages/frontend && bun run lint
          cd packages/backend && bun run lint

      - name: Format check
        run: |
          bun run format:check
          cd packages/frontend && bun run format
          cd packages/backend && bun run format

      - name: Type check
        run: |
          cd packages/frontend && bun run typecheck
          cd packages/backend && bun run typecheck

      - name: Build frontend
        run: cd packages/frontend && bun run build

      - name: Test backend
        run: cd packages/backend && bun run test

      - name: Test coverage
        run: cd packages/backend && bun run test:cov