name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Install dependencies
        run: bun install

      - name: Format check
        run: bun run format:check

      - name: Lint
        run: bun run lint:strict

      - name: Type check backend
        working-directory: ./packages/backend
        run: bun run typecheck

      - name: Type check frontend
        working-directory: ./packages/frontend
        run: bun run typecheck

      - name: Test backend
        working-directory: ./packages/backend
        run: bun run test

      - name: Test frontend
        working-directory: ./packages/frontend
        run: bun run test
